name = "apk-builder-api"
main = "index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "BUILD_QUEUE"
class_name = "BuildQueue"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["BuildQueue"]

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "4b50cc0bff95441f9db1a33248786280"

[[kv_namespaces]]
binding = "LOGS"
id = "5d674bf790424724a6a806d7bef6572b"
